name: flutter_core
framework: flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:

  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.7.1
  http: ^1.3.0
  flutter_skeleton_ui: ^0.0.6
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  date_picker_timeline: ^1.2.6
  geolocator: ^14.0.1
  google_maps_flutter: ^2.10.0
  google_places_flutter: ^2.0.6
  shared_preferences: ^2.5.2
  change_app_package_name: ^1.4.0
  country_picker: ^2.0.27
  jiffy: ^6.3.2
  flutter_widget_from_html: ^0.17.1
  connectivity_plus: ^6.1.3
  flutter_otp_text_field: ^1.4.0+2
  syncfusion_flutter_charts: ^32.1.21
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1

  shimmer: ^3.0.0
  timeago: ^3.7.1
  timeago_flutter: ^3.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.3.1
  mime_type: ^1.0.1


  talker: ^5.0.1
  talker_dio_logger: ^5.0.1
  talker_flutter: ^5.0.1
  talker_riverpod_logger: ^5.0.1
  flutter_secure_storage: ^10.0.0
  easy_localization: ^3.0.7+1
  internet_connection_checker: ^3.0.1

  # firebase
#  firebase_messaging: ^15.2.2
#  firebase_analytics: ^11.5.0
#  firebase_core: ^3.14.0
#  firebase_crashlytics: ^4.3.7

  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  animated_splash_screen: ^1.3.0

  # network
  dio: ^5.8.0+1
  dio_intercept_to_curl: ^0.2.0
  dio_cache_interceptor: ^4.0.3
  http_cache_hive_store: ^5.0.1

  # state management
  flutter_riverpod: ^2.6.1
  riverpod_infinite_scroll_pagination: ^1.0.3

  # device
  package_info_plus: ^9.0.0
  device_info_plus: any
  permission_handler: ^12.0.0+1
  open_filex: ^4.7.0


  #parser
  jwt_decoder: ^2.0.1
  dart_mappable: ^4.5.0
  json_annotation: ^4.9.0

  #ui
  toggle_switch: ^2.3.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_calendar_carousel: ^2.5.4
  hijri: ^3.0.0
  hijri_picker:
    git: https://github.com/ahmedoid/hijri_picker.git
  font_awesome_flutter: ^10.8.0
  dart_debouncer: ^1.1.1
  #  flutter_pdfview: ^1.4.3
  #  pdf: ^3.11.3
  gif_view: ^1.0.3
  otp_pin_field: ^1.4.1
  cached_network_svg_image: any

  #utils
  auto_route: ^10.0.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  multiple_result: ^5.2.0
  velocity_x: ^4.3.1
  remove_emoji_input_formatter: ^0.0.1+1
  material_design_icons_flutter: ^7.0.7296
  flutter_screenutil: ^5.9.3
  path_provider: ^2.1.5
  crypto: ^3.0.6
  local_auth: ^3.0.0
  cryptography: ^2.7.0
  root_checker_plus: ^1.0.0
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  flutter_image_compress: ^2.4.0


  auto_route_generator: ^10.2.3
  build_runner: ^2.5.0
  custom_lint: any
  dart_mappable_builder: ^4.5.0
  json_serializable: ^6.7.0
  another_flutter_splash_screen:  ^1.2.1
  youtube_player_flutter: ^9.1.1


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by  the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter


dependency_overrides:
  skeletonizer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/svg/bottomnav/
    - assets/svg/



  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800

    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoKufiArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoKufiArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoKufiArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoKufiArabic-Black.ttf
          weight: 900